### ISSUE TITLE
Travis: Rubocop should be run after the RSpec tests

### ISSUE THREAD

**Issue by mvidner** [yast/yast-yast2#324] opened 2015-01-21 16:18 UTC
Rubocop should be run after the RSpec tests, because its reports are less severe.

Also, if it currently fails, the failure is hidden in the travis log, because Travis does not stop the script. Maybe this will be a problem with the other checks once they get moved to the top?

**Comment by lslezak** [comment] 2015-01-21 17:30
The problem is that Travis does not support failing fast (well, there is a workaround, see https://github.com/travis-ci/travis-ci/issues/1066).

The question is do we want that? I mean, you could fix a testsuite issue, then find out there is a rubocop issue, then it does not install, etc...

On the other hand finding multiple issues in a single long log is not easy, you can easily overlook something. From that perspective it might be better to fail early...

**Comment by dgdavid** [comment] 2020-02-06 12:19
@mvidner, @lslezak, 

If I'm not wrong, this is outdated, right? Could you have a look, put the relevant information if needed, and close it if possible?

**Comment by ancorgs** [comment] 2021-03-12 14:47
This looks like an old outdated conversation to me. Closing.

**Closed by ancorgs** 2021-03-12 14:47 UTC
